/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.salle.custommoodle.view;

/**
 *
 * @author Red
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        
        initComponents();
        this.setTitle("Choose a fighter");
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAlumno = new javax.swing.JButton();
        bMateria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAlumno.setText("Alumno");
        bAlumno.setToolTipText("");
        bAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(bAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 86, 82, 38));

        bMateria.setText("Materia");
        bMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(bMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 86, 77, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlumnoActionPerformed
        // TODO add your handling code here:
        StudentWindow student= new StudentWindow();
        student.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bAlumnoActionPerformed

    private void bMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMateriaActionPerformed
        // TODO add your handling code here:
         TopicWindow  materia= new TopicWindow();
        materia.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlumno;
    private javax.swing.JButton bMateria;
    // End of variables declaration//GEN-END:variables
}
