/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.salle.custommoodle.view;

import edu.salle.custommoodle.businesslogic.StudentBLO;
import edu.salle.custommoodle.model.Student;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Red
 */
public class StudentWindow extends javax.swing.JFrame {

    /**
     * Creates new form StudentWindow
     */
    private StudentBLO studentBLO= new StudentBLO();
    public StudentWindow() {
        
        initComponents();
        setLocationRelativeTo(null);
        studentBLO.load();
        refreshTable(studentBLO.findAll());
        iconizar();
    }
    private void iconizar(){
        ImageIcon exit= new ImageIcon(getClass().getResource("/icons/exit.png"));
        ImageIcon exitx= new ImageIcon(exit.getImage().getScaledInstance(bExit.getWidth(), bExit.getHeight(), Image.SCALE_DEFAULT));
        bExit.setIcon(exitx);
        
        ImageIcon ser= new ImageIcon(getClass().getResource("/icons/search.png"));
        ImageIcon serc= new ImageIcon(ser.getImage().getScaledInstance(bSearch.getWidth(), bSearch.getHeight(), Image.SCALE_DEFAULT));
         bSearch.setIcon(serc);
         
         
         ImageIcon ref= new ImageIcon(getClass().getResource("/icons/reload.png"));
        ImageIcon refr= new ImageIcon(ref.getImage().getScaledInstance( bRefresh.getWidth(),  bRefresh.getHeight(), Image.SCALE_DEFAULT));
         bRefresh.setIcon(refr);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();
        bSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tStudents = new javax.swing.JTable();
        bRefresh = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/icons/main.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jLabel2.setText("Last name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        tfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        bSave.setBackground(new java.awt.Color(77, 188, 141));
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        bSearch.setBackground(java.awt.SystemColor.window);
        bSearch.setForeground(java.awt.SystemColor.window);
        bSearch.setBorder(null);
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });
        getContentPane().add(bSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 30, 30));

        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, -1));

        bUpdate.setBackground(new java.awt.Color(230, 207, 45));
        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        bDelete.setBackground(new java.awt.Color(217, 104, 89));
        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        tStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(tStudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, 130));

        bRefresh.setBackground(java.awt.SystemColor.window);
        bRefresh.setBorder(null);
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 40, 40));

        bExit.setBackground(java.awt.SystemColor.window);
        bExit.setForeground(java.awt.SystemColor.window);
        bExit.setBorder(null);
        bExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 40, 40));
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 240, 20));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastNameActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed

String name = tfName.getText();
String lastName= tfLastName.getText();
String namex= name.replaceAll(" ","");
String lastNamex= lastName.replaceAll(" ", "");
        if (namex.equals("") ) {
            JOptionPane.showMessageDialog(null,"You need to fill name & lastname   plz");
            
        }
        else
        {if(lastNamex.equals(""))
        {
            JOptionPane.showMessageDialog(null,"You need to fill name & lastname  plz");
        }
        else
        {
            Student student = new Student(name,lastName);
studentBLO.save(student);
tfName.setText("");
tfLastName.setText("");
        }
        }

    }//GEN-LAST:event_bSaveActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed

//        String id= tfID.getText();
//        Student student= studentBLO.find(id);
//        if (student!=null) {
//            tfName.setText(student.getName());
//            tfLastName.setText(student.getLastname());
//            tfID.setText("");
//        }
//               String  lastname=tfLastName.getText().trim();
//               List <Student> studentList= studentBLO.findByLastName(lastname);
//               refreshTable(studentList);
String lastname=tfSearch.getText().trim();
if(!lastname.isEmpty())
{
               refreshTable(studentBLO.findByLastName(lastname));
}
else
{
    JOptionPane.showMessageDialog(null,"You need to fill the search text field  plz");
}
               
    }//GEN-LAST:event_bSearchActionPerformed
private void refreshTable(List<Student> studentList)
{
    clearTable();
    
    DefaultTableModel dtm= (DefaultTableModel)tStudents.getModel();
    Object[] emptyRow={""};
    for (int i = 0; i < studentList.size();i++) {
        dtm.addRow(emptyRow);
        dtm.setValueAt(studentList.get(i).getId(),i,0);
        dtm.setValueAt(studentList.get(i).getName(),i,1);
        dtm.setValueAt(studentList.get(i).getLastname(),i,2);
    }
}
private void clearTable(){
    DefaultTableModel dtm= (DefaultTableModel)tStudents.getModel();
    while(dtm.getRowCount()>0)
    {
        dtm.removeRow(0);
    }
}
    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
Student busq= new Student();
        busq.setId(tfID.getText());
        busq.setName(tfName.getText());
        busq.setLastname(tfLastName.getText());
         if(! busq.getId().isEmpty() && ! busq.getName().isEmpty() && ! busq.getLastname().isEmpty())
{
              studentBLO.update(busq);
        tfName.setText("");
        tfLastName.setText("");
        tfID.setText("");
}
else
{
    JOptionPane.showMessageDialog(null,"You need to fill all the gaps");
}
        
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        refreshTable(studentBLO.findAll());
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        Student reprobado= new Student();
        reprobado.setId(tfID.getText());
        reprobado.setName(tfName.getText());
        reprobado.setLastname(tfLastName.getText());
        if(!reprobado.getId().isEmpty() && !reprobado.getName().isEmpty() && !reprobado.getLastname().isEmpty())
{
              studentBLO.delete(reprobado);
              tfName.setText("");
        tfLastName.setText("");
        tfID.setText("");
}
else
{
    JOptionPane.showMessageDialog(null,"You need to fill all the gaps");
}
        
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        studentBLO.commitChanges();
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tStudents;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
